### ISSUE TITLE
Code style

### ISSUE THREAD

**Issue by lndbaryshnikov** [lndbaryshnikov/resume#16]
Заменил одинарные кавычки на двойные в pug файлах.

**Comment by Nelliza** [comment]
Еще в **index.pug** остались одни, и также в стилевых файлах наоборот замени двойные кавычки одинарными (посмотри в файлах **contact.scss** и **progress-list-item.scss**)

**Comment by lndbaryshnikov** [comment]
Исправил)

**Comment by lndbaryshnikov** [comment]
А в **pug**-файлах строго двойные везде, даже если это js?

**Comment by lndbaryshnikov** [comment]
А в **js** - все кавычки должны быть одинарные, даже если это html код (например в JQuery)?

**Comment by Nelliza** [comment]
> А в **js** - все кавычки должны быть одинарные, даже если это html код (например в JQuery)?
> Например
> 
> ```js
> $('<span class=\'ink\'></span>')
> ```

Нет, здесь думаю двойные нужны внутри атрибута )

**Comment by Nelliza** [comment]
> Исправил)

Пока другие issues правил, новых кавычек наплодил ) Пройдись пожалуйста везде

**Comment by lndbaryshnikov** [comment]
> Пока другие issues правил, новых кавычек наплодил ) Пройдись пожалуйста везде

Да уж, хочется верить что это вебштормовский **code formatting**, не думал что пропущу кучу одинарных кавычек.. Исправил)

**Comment by Nelliza** [comment]
CSS-стандарты:
![1](https://user-images.githubusercontent.com/19621113/74448409-f5d4b500-4e8b-11ea-9fcc-7b90bfa5761a.png)

![2](https://user-images.githubusercontent.com/19621113/74448603-4c41f380-4e8c-11ea-993a-6fe37335d6b0.png)
![3](https://user-images.githubusercontent.com/19621113/74448610-4e0bb700-4e8c-11ea-94c3-d032065142b5.png)
По-моему, тут описан как раз твой случай про хардкод неочевидных отступов ) Могу сказать, что использовать таким образом нагромождение модификаторов только для того, чтобы назначить им разные отступы в угоду PerfectPixel - точно не комильфо )

**Comment by Nelliza** [comment]
![1](https://user-images.githubusercontent.com/19621113/74449490-ad1dfb80-4e8d-11ea-9e1a-985d1900ea40.png)

На js-код, вставляемый в pug-файлы, распространяются правила стайлгайда от Airbnb, поэтому в конце выражений следует также проставлять знак `;`
Пройдись пожалуйста по всему проекту на предмет исправлений

**Comment by Nelliza** [comment]
**page.pug**
![2](https://user-images.githubusercontent.com/19621113/74449668-f0786a00-4e8d-11ea-85c0-b317c33537a2.png)
Здесь не нужны кавычки для значений `level`

**Comment by Nelliza** [comment]
**software-item.pug**
![1](https://user-images.githubusercontent.com/19621113/74683517-4294f480-51da-11ea-80d7-fb6177b0a053.png)
Согласно [п. 22.3 стайлгайда от Airbnb](https://github.com/leonidlebedev/javascript-airbnb#coercion--numbers), для приведения к числу правильнее воспользоваться `Number` или методом `parseInt` с указанием системы счисления

**Comment by lndbaryshnikov** [comment]
Ты наверно не стянула последние изменения, миксин немного выглядит по-другому, но ошибку исправил, убрал вообще приведение к числу, т.к. без надобности)
