### ISSUE TITLE
Px -> rem

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/resume#18]
Для адаптивной верстки удобно использовать `rem` - в дальнейшем тебе не нужно менять вручную размеры каждого из элементов для адаптивной верстки, достаточно только поменять размер шрифта корневого элемента. Об этом говорится также у нас в [CSS-стандартах (п. 5)](https://github.com/fullstack-development/front-end-best-practices/blob/99766f0d4d37ed8e0529f6e5d34a76f62d1071d9/CSS/fonts.md).

Как вариант, можно воспользоваться для этого расширением _**px to rem**_

**Comment by Nelliza** [comment]
При этом для ширин, которые должны резиниться, мы используем `%`-ты, пройдись плиз тоже по всему проекту

**Comment by lndbaryshnikov** [comment]
Возник вопрос, а как поступать с переопределенными компонентами, с тем же **Datepicker** от JQuery UI во втором задании. Переопределяются ведь только некоторые размеры, наверное, логичнее ставить там **px**, т.к. будет непропорциональное изменение размеров, если только часть в **rem**?

**Comment by Nelliza** [comment]
Думаю, надо по ситуации смотреть, возможно, это действительно будет логичнее при работе со сторонними плагинами. Я переопределяла в `rem`-ах, проблем не возникало, но плагины разные бывают )
