### ISSUE TITLE
readme

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#25]
Привет! Меня зовут Артём и я твой проверяющий. Будет очень круто, если по окончании каждой итерации твоих исправлений я буду узнавать об этом в telegram. Так же, буду признателен, если ты будешь тестировать проект после исправлений, править сразу по всему проекту и не упускать замечаний, которые я тебе оставляю. В добрый путь:)

![image](https://user-images.githubusercontent.com/46949445/88395188-58ca6080-cdc9-11ea-8217-e85e52150ac6.png)
Из этого "Шаблон резюме. Адаптивная веб-страница." назначение проекта вообще не ясно)

Ты пробовал разворачивать с нуля проект по своей инструкции?
![image](https://user-images.githubusercontent.com/46949445/88395294-82838780-cdc9-11ea-9cd8-60c47137c772.png)

**Comment by lndbaryshnikov** [comment]
Привет, Артем! Очень приятно)
Задачу понял, как будет готово - отпишусь в телеграм!

**Comment by lndbaryshnikov** [comment]
> Ты пробовал разворачивать с нуля проект по своей инструкции?

Я так думаю тут дело в том, что не было команды `cd` в папку с проектом перед `npm install`? Добавил)
