### ISSUE TITLE
pp

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#26]
Чет жесть какая-то у тебя с проверкой на pp. Не получается проверить, не пойму в чем причина. Нужно поправить за выходные
В общем, смотри какой алгоритм проверки макета по этому правилу:
1. Ставим в devtools ширину окна = ширине макета (1920px в нашем случае)
2. В расширении ставим x = 0,  y = 0, размер макета = 1
3. У нас должно все совпасть

**Comment by lndbaryshnikov** [comment]
Просто верстал для pp не под 1920. Подогнал все под 1920.
![image](https://user-images.githubusercontent.com/48272925/88474305-bbd50800-cf2d-11ea-8725-7f4fcbd84745.png)
![image](https://user-images.githubusercontent.com/48272925/88474312-d14a3200-cf2d-11ea-9a38-3b250e306498.png)
![image](https://user-images.githubusercontent.com/48272925/88474314-d9a26d00-cf2d-11ea-98f5-ed5403d58d4f.png)
![image](https://user-images.githubusercontent.com/48272925/88474316-e1621180-cf2d-11ea-87b1-3ab71a2c8b96.png)

**Comment by artamonJr** [comment]
Подправь немного текст
![image](https://user-images.githubusercontent.com/46949445/88543742-14390200-d021-11ea-8313-de0ce59b3dbf.png)

Еще момент - высота макета 2715px, у тебя макет 2678px. Различие большое, нужно поправить

**Comment by lndbaryshnikov** [comment]
> Подправь немного текст

Вот тут у меня были небольшие неточности во втором пункте раздела, но не так сильно как у тебя.. Подогнал второй, теперь должно быть прям идеально. Если что мой макет лежит в `src/assets/images`, может как-то по-разному сконвертировалось, бывает фотошоп иногда чудачит.

**Comment by imin314** [comment]
Тут проверила, все ок. Потом попросим Артема закрыть всё разом.
