### ISSUE TITLE
bugs/ui

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#27]
Ширина страницы 320px, ширина секции 253, ширина внутреннего блока 263 и итог = контент вылазиет за пределы блока. Нужно поглядеть верстку от 320px до 1920px и проверить, чтобы контент не вылазил за пределы блоков.
Тут есть одно просто правило: *ширина внутреннего блока не может быть больше ширины внешнего*
![Peek 2020-07-24 17-00](https://user-images.githubusercontent.com/46949445/88399285-5539d800-cdcf-11ea-92f4-4ac3ee844eec.gif)

Переполнение тоже нужно глянуть
![image](https://user-images.githubusercontent.com/46949445/88399403-7b5f7800-cdcf-11ea-8d88-4fb206baeb07.png)

В макете тут все выровнено вдоль горизонтальной оси, у тебя все играет
![image](https://user-images.githubusercontent.com/46949445/88399614-d1ccb680-cdcf-11ea-9c73-b28e321540b2.png)

Кружочки слипаются, это плохо
![image](https://user-images.githubusercontent.com/46949445/88400079-74853500-cdd0-11ea-8ed5-3a6e25074e42.png)

**Comment by lndbaryshnikov** [comment]
Все баги исправлены. 
* С переполнением решил вопрос просто разрывом в любом месте слова. Потому что даже при 1920px с этим Константином все выходит за рамки, то есть по сути это недочет макета. При меньших разрешениях уменьшил размер шрифта
* Кружочки не больше слипаются
* Вылезание контента за пределы блоков поправил

**Comment by lndbaryshnikov** [comment]
Все баги исправлены. 
* С переполнением решил вопрос просто разрывом в любом месте слова. Потому что даже при 1920px с этим Константином все выходит за рамки, то есть по сути это недочет макета. При меньших разрешениях уменьшил размер шрифта
* Кружочки больше не слипаются
* Вылезание контента за пределы блоков поправил

**Comment by artamonJr** [comment]
> Потому что даже при 1920px с этим Константином все выходит за рамки

Улыбнуло, спасибо :)

Имя университета тоже может быть похожим на Константина, поэтому нужно пройтись по всем подобным местам и посмотреть переполнение
![image](https://user-images.githubusercontent.com/46949445/88544871-c3c2a400-d022-11ea-8a96-30bad669eda2.png)

Если добавим еще один скилл, то поедет верстка(
![image](https://user-images.githubusercontent.com/46949445/88544961-f10f5200-d022-11ea-919c-a6e49e297715.png)

Тут тоже контент формируется автоматически, а поэтому нужно предусмотреть и такой случай
![image](https://user-images.githubusercontent.com/46949445/88545365-90344980-d023-11ea-92ef-1774430ca58a.png)

**Comment by imin314** [comment]
Проверено, можно закрыть
