### ISSUE TITLE
basic iteration(html, css, bem)

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#28]
meta keywords забыл

index, style и main - как будто от разных страниц файлы) давай чтобы было одинаково? Есть index.html, у нее есть index.css и тд.
![image](https://user-images.githubusercontent.com/46949445/88546049-8101cb80-d024-11ea-9da3-8c5c14bbab8a.png)

**Comment by artamonJr** [comment]
Как-то не нравится мне верстка структуры сайта с этим flex: column
- Вот что происходит, когда добавляю еще одну секцию:
![image](https://user-images.githubusercontent.com/46949445/88650876-cfb96f00-d0d1-11ea-85df-c8bb0f0bdd8b.png)
- + у тебя ограничена максимальная высота, что тоже не очень хорошо. Получается у тебя при достижении этой высоты, блоки будут уходить вправо и будет полоса прокрутки
- Так же много всяких модификаторов, которые нужны, к примеру, для изменения ширины блока на сотые процента
![image](https://user-images.githubusercontent.com/46949445/88651412-48b8c680-d0d2-11ea-93ee-eb6874c703a1.png)
Может лучше разделить макет на две колонки и в колонках уже будут различные секции? Мне кажется ты избавишься от всех минусов, что я выше описал + код читать будет легче и от ненужных отступов тоже избавишься.
Еще одно замечание. Если у тебя, к примеру, все однотипные блоки шириной в 20px, а один в 21px, то лучше сделать все по 20px и не плодить модификаторы или доп. классы, чтобы соответствовать pp. Скорее всего, если такое будет, то это огрех дизайнера.

Для этого блока не очень удачно выбрано имя для этого блока. Header - это о части, которая повторяется от страницы к странице, например вверху каждой страницы.
![image](https://user-images.githubusercontent.com/46949445/88652343-5cb0f800-d0d3-11ea-86a6-16b39413b8a3.png)

- Это точно не должно быть фоновой картинкой сделано, тк по сути, фото будет являться частью контента, без которого твое резюме особо смысла иметь не будет)
- Имя для элемента тоже нужно поменять
![image](https://user-images.githubusercontent.com/46949445/88653264-7ef74580-d0d4-11ea-8206-25fa39f0a510.png)

Зачем плодить доп. теги, если можно избавиться от header__name? И тебе работы меньше, и код станет проще читать
![image](https://user-images.githubusercontent.com/46949445/88653666-0a70d680-d0d5-11ea-9488-4bea2bc28834.png)

И попытайся избавиться от множества отступов справа и слева, по типу этого. Подозреваю, что отступ можно вынести к ближайшему родителю, чтобы иметь один отступ вместо, скажем, пяти
![image](https://user-images.githubusercontent.com/46949445/88653880-4f950880-d0d5-11ea-82d5-ee4b5013d33a.png)

Такого рода иконки лучше сразу в фотошопе сделать одинакового размера, чтобы не было потом всяких таких модификаторов, которые меняют ширину на несколько пикселей
![image](https://user-images.githubusercontent.com/46949445/88654600-40628a80-d0d6-11ea-979a-5d7f34134f9a.png)

*Вообще, нужно стараться делать как можно проще, но чтобы эта простота в то же время не ухудшала ясность кода*
Если можешь сделать один тег вместо двух, то лучше сделать один. Если можешь нарезать картинки под один размер, чтобы не усложнять html и css код, то нужно нарезать

Что за компонент такой, в котором один текст? :)
![image](https://user-images.githubusercontent.com/46949445/88655147-05148b80-d0d7-11ea-8c61-a66bb6dc6ed7.png)
Очень сложная разметка для понимания, если честно. Давай я попробую натолкнуть тебя на более элегантный подход(конечно же по моему мнению:))
Ты выделил это в элемент section, блока page, но управляешь его размерами и отступами через модификаторы.
![image](https://user-images.githubusercontent.com/46949445/88655515-8d932c00-d0d7-11ea-8bb0-7788d0930d21.png)
У нас в стандартах в [6](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md) пункте есть об этом, думаю стоит переделать. И дальше, у тебя тут идет компонент block-header, тут все окей, это часто повторяющийся блок. И мы имеем тут текст, который может быть стилизован 1) каскадом от блока выше в иерархии 2) быть часть компонента profile, к примеру, тут можешь сделать выбор сам

**Comment by artamonJr** [comment]
Ну вот. Отличная работа проделана, молодец!

Настолько сильно не нужно переживать о pp) Пару пикселей отклонения допустимо. 
![Peek 2020-08-06 09-53](https://user-images.githubusercontent.com/46949445/89500748-e2672e80-d7ca-11ea-8f73-7272cea5e140.gif)
Пройдись еще разок и посмотри на такие моменты

А зачем тебе тут span?
![image](https://user-images.githubusercontent.com/46949445/89501041-5acdef80-d7cb-11ea-99b7-cd31385c90a4.png)

Зачем тут модификатор?
![image](https://user-images.githubusercontent.com/46949445/89501155-89e46100-d7cb-11ea-85a4-bcae679cbab8.png)
![image](https://user-images.githubusercontent.com/46949445/89501382-eba4cb00-d7cb-11ea-9f65-7a93a0d2097a.png)

Почему это выделил в отдельный блок? Этот блок может использован где-то в другом месте быть?
![image](https://user-images.githubusercontent.com/46949445/89501620-535b1600-d7cc-11ea-9977-261874a94e91.png)

skills-item тоже не может быть использован нигде, кроме как тут, поэтому выносить его в отдельный блок - неправильно
![image](https://user-images.githubusercontent.com/46949445/89502008-f6139480-d7cc-11ea-9920-1e8a8f008fe6.png)

- По бэм, у блока не должно быть внешних отступов. Из-за того, что ты не учел, что браузеры могут добавлять к тегам свои отступы, получается, что ты нарушаешь этим самым принципы бэм)
- Также, не нужно полагаться на левый паддинг у ul. В другом браузере он может быть другим, или его может не быть вообще
![image](https://user-images.githubusercontent.com/46949445/89502334-818d2580-d7cd-11ea-8288-82ed2b54a42c.png)

Также еще по отступам. Смотри, у меня в браузере к body добавляются отступы в 8px (у тебя я подозреваю тоже самое) и дальше ты задаешь padding блоку resume и танцуешь от этого, когда проверяешь pixel perfect. А что если, в safari к примеру, будет отступ у body 20px? Ответ - твоя верстка полетит к чертям)
![image](https://user-images.githubusercontent.com/46949445/89502531-d335b000-d7cd-11ea-84c0-375881b4717f.png)

Посмотри разрешенный контент у ul
![image](https://user-images.githubusercontent.com/46949445/89502697-1132d400-d7ce-11ea-93eb-47f4ec7a1211.png)

**Comment by artamonJr** [comment]
слишком длинное название) лучше item-link
![image](https://user-images.githubusercontent.com/46949445/89545330-dfd8f900-d80b-11ea-84c0-ee948029e45d.png)

это зачем?
![image](https://user-images.githubusercontent.com/46949445/89545678-55dd6000-d80c-11ea-99cf-8ed8f8d6ea1d.png)

этот список может быть чего угодно, поэтому progress-list не очень хорошее название
![image](https://user-images.githubusercontent.com/46949445/89546140-eae05900-d80c-11ea-90f7-5c817b630be4.png)

тут аналогично, это не блок
![image](https://user-images.githubusercontent.com/46949445/89546180-f9c70b80-d80c-11ea-9377-83d7792e1fed.png)

**Comment by artamonJr** [comment]
Это нельзя одним элементом сделать item-period?
![image](https://user-images.githubusercontent.com/46949445/89612910-a9da5a00-d889-11ea-9ac1-ff6095a17f6d.png)

Зачем тут ненужный модификатор и стили? разве span не наследует color?
![image](https://user-images.githubusercontent.com/46949445/89613039-f9b92100-d889-11ea-8960-559c8153278e.png)

Почему у тебя все есть section, а это div?)
![image](https://user-images.githubusercontent.com/46949445/89613094-15242c00-d88a-11ea-8cd9-d603948ac84f.png)

Нужен семантично более подходящий тег
![image](https://user-images.githubusercontent.com/46949445/89613128-29682900-d88a-11ea-975c-c431ac348d3f.png)

**Comment by imin314** [comment]
> Зачем тут ненужный модификатор и стили? разве span не наследует color?

Сейчас цвет заголовка в progress-list устанавливается из json:
https://github.com/lndbaryshnikov/resume/blob/038772ed405fb43aec30d53419fd4fa3ec42bb77/src/assets/data/content.json#L32
Надо сделать так, чтобы модификатор с цветом устанавливался в блоках education и experience.

**Comment by imin314** [comment]
Мне кажется, настройка nameColor должна задаваться не для каждого элемента, а глобально для всего блока. Можно, например, в блок передавать { items: [], nameColor: 'blue' }.

А еще остались довольно специфические модификаторы для того, чтобы подогнать верстку под PP: 
https://github.com/lndbaryshnikov/resume/blob/7ec34ed36b3dafda22b31ba712c6b590dab52b84/src/components/progress-list/progress-list.scss#L27-L36

Если блок часто используемый, а дизайнер не особо заморачивался с выравниванием и отступами, то придется добавлять на каждый случай модификаторы for-... В таких случаях можно выбрать несколько вариантов отступов, которыми можно более менее покрыть разные кейсы использования блока. Например, с нулевым маржином, с отступами в 0.15rem. Но в данном случае для разных отступов в списках Education и Experience нет логичного объяснения, поэтому можно для всех progress-list__item оставить один margin.

**Comment by imin314** [comment]
Можно закрывать
