### ISSUE TITLE
package.json

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#30]
Если ты не планируешь свой проект публиковать в реестре npm, то тебе нужно добавить private поле и удалить все поля, кроме scripts, dep, devDep

Раздели devDep и dep опираясь на [статью](https://docs.npmjs.com/specifying-dependencies-and-devdependencies-in-a-package-json-file)

Думаешь можно будет использовать твои скрипты dev, watch? Мне кажется, что при разработке, достаточно использовать webpack dev server
![image](https://user-images.githubusercontent.com/46949445/89613550-291c5d80-d88b-11ea-927e-5c24a73c2c1c.png)

**Comment by imin314** [comment]
Здесь еще надо актуализировать README: удалить неиспользуемые, еще можно добавить команду для развертывания проекта на ghPages.

**Comment by imin314** [comment]
Проверила, всё ок
