### ISSUE TITLE
detailed iteration (html/pug, css/scss, bem)

### ISSUE THREAD

**Issue by artamonJr** [lndbaryshnikov/resume#32]
По нашим стандартам, шрифты должны быть woff2 и woff
![image](https://user-images.githubusercontent.com/46949445/89614115-6df4c400-d88c-11ea-96af-637304f7f05b.png)

Что тут фавиконка делает?
![image](https://user-images.githubusercontent.com/46949445/89614164-8bc22900-d88c-11ea-8a54-241d592e9a0f.png)

pp картинку лучше или убрать или вынести из src, тк она имеет косвенное отношение к проекту
![image](https://user-images.githubusercontent.com/46949445/89614199-9f6d8f80-d88c-11ea-8ab4-b725b457cfa1.png)

Если среди этих переменных есть те, которые задают основную палитру сайта, то нужно почитать за цветовую [палитру](https://material-ui.com/customization/color/#picking-colors) и дать соответствующие имена переменным
![image](https://user-images.githubusercontent.com/46949445/89614546-5964fb80-d88d-11ea-98e8-b95534ce36bc.png)

- Шрифт для html лучше вынести в переменную и задать одним свойством font
- почему ты на тег html вешаешь resume-background? это же не резюме?) лучше нормально имя придумать для этой переменной
- ширину лучше у боди ограничивать, тк html это твой корень по сути и его лучше не трогать
- зачем тут margin: auto, если ниже он перетирается?
- нужно перевести все px -> rem, кроме медиазапросов
- поправь линтер, чтобы ругал тебя за то, что ты оставляешь много пустых строк в конце :)
![image](https://user-images.githubusercontent.com/46949445/89615564-93370180-d88f-11ea-817e-856044a4c91c.png)

- старайся использовать строгое сравнение, даже если оно тут не приводит типы, то это хорошая привычка, которая позволит тебе избежать многих проблем с js)
- лучше придерживаться одного стиля, если начал задавать weight в числах, то продолжай в том же духе. Что за weight: bold?
![image](https://user-images.githubusercontent.com/46949445/89615797-ed37c700-d88f-11ea-9444-e345b5259b46.png)

**Comment by imin314** [comment]
> Если среди этих переменных есть те, которые задают основную палитру сайта, то нужно почитать за цветовую палитру и дать соответствующие имена переменным. 
Мне кажется, лучше цвет текста переименовать в $color-text-primary, а для второго цвета убрать -light. У тебя получится набор цветов: primary, secondary и text-primary.
https://github.com/lndbaryshnikov/resume/blob/038772ed405fb43aec30d53419fd4fa3ec42bb77/src/styles/variables/colors.scss#L3-L4

**Comment by imin314** [comment]
Можно закрывать
