### ISSUE TITLE
БЭМ

### ISSUE THREAD

**Issue by Nelliza** [lndbaryshnikov/resume#7]
Напишу пока общие замечания по проекту, чтобы сначала "причесать" его для дальнейшей работы:

блоки по БЭМ должны быть выделены в отдельные директории, именуемые аналогично названиям блоков. Все блоки при этом оформляются pug-миксинами. В директории каждого из блоков должны лежать только файлы разметки, стилей и скриптов самого блока.
В самом pug-файле должен быть только миксин, который возвращает одноименный блок. Все элементы при этом должны находиться внутри своего родительского блока.
То же касается и стилевых файлов — там должны присутствовать только стили самого блока и вложенных в него элементов.
При этом в отдельные файлы достаточно выносить сами блоки вместо каждого элемента

**Comment by Nelliza** [comment]
Сразу еще добавлю, чтобы потом заново не переписывать все - использование примесей по нашим стандартам не допускается ([пункты 5-6 CSS-стандартов]( https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md))

**Comment by Nelliza** [comment]
Хорошая работа проделана, но остались еще моменты:
1. Pug-миксин должен возвращать **блок**, называемый аналогично имени самого компонента. Сейчас во многих миксинах не так (для примера назову **contact.pug**, **education-item.pug**, **experience.pug**, **skills-item.pug**, поищи плиз и исправь по всему проекту)
2. Использование примесей по нашим стандартам не допускается, и вот почему: [п.п. 5-6 CSS-стандартов по БЭМ](https://github.com/fullstack-development/front-end-best-practices/blob/27f4f54390662f5368dc2ad4687c8db6a9bdf689/CSS/bem.md). У тебя в блоке **experience** используются, посмотри также везде в проекте
3. **body**, **html**, **layout-grid**, **section-wrapper** - это не отдельные компоненты, для них не предусмотрено блоков, это просто стили, ты можешь эти общие стили вынести в отдельный файл (например, **base.scss**)

**Comment by Nelliza** [comment]
Компонент **profile**
![1](https://user-images.githubusercontent.com/19621113/73072615-7c6a2800-3ec6-11ea-8e38-23dd1b476405.png)
Такая вложенность по БЭМ запрещена, т.к. здесь нарушается принцип инкапсуляции: правила одного блока начинают влиять на другой блок. Хотя по БЭМ блоки должны быть полностью автономными и могут влиять только на собственные элементы

**Comment by Nelliza** [comment]
По БЭМ запрещено задавать внешнюю геометрию блокам, у тебя сейчас многим блокам заданы внешние отступы. Способ решения подобной проблемы описан у нас в [CSS-стандартах (п. 6)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)

**Comment by Nelliza** [comment]
**index.pug**
![1](https://user-images.githubusercontent.com/19621113/73628749-2a619900-4662-11ea-9f10-564f99bf273a.png)
Здесь модификаторы используются без основного элемента

**Comment by Nelliza** [comment]
> По БЭМ запрещено задавать внешнюю геометрию блокам, у тебя сейчас многим блокам заданы внешние отступы. Способ решения подобной проблемы описан у нас в [CSS-стандартах (п. 6)](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/bem.md)

Для блоков **contact-item**, **progress-list-item** и **section-wrapper** еще остались внешние отступы

**Comment by lndbaryshnikov** [comment]
Возник вопрос по поводу последнего коммита. Объединил **layout-grid** и **section-wrapper** в один блок **page**. Стили были в base.scss, так как ты сказала, что они не возвращают блоков, следовательно им не место в **components/**. Но потом решил логичней будет создать миксин для **page**. Создал, закинул в папку с компонентами. И вот теперь вопрос с зависимостями, по БЭМ все зависимости должны быть включены в блок, миксины подключил, а стилевые файлы нужно автоимпортом. Но и **page.js** создавать ради автоимпорта кажется не совсем красиво, и вручную в **page.scss** тоже не вариант, так как вручную. Что можно придумать в данном случае?) И второй вопрос, так как я организовал как миксин, то он получается очень захардкоженный, что плохо, и передавать все настройки в аргументах тоже, сомневаюсь, что хорошая идея...

**Comment by Nelliza** [comment]
> ... И вот теперь вопрос с зависимостями, по БЭМ все зависимости должны быть включены в блок, миксины подключил, а стилевые файлы, как обговаривалось, нужно автоимпортом. Но и **page.js** создавать ради автоимпорта кажется не совсем красиво, и вручную в **page.scss** тоже не вариант, так как вручную. Что можно придумать в данном случае?)

Немного не поняла, какие стили тебе нужно подключать дополнительно, они же и так все автоимпортятся у тебя? )

**Comment by Nelliza** [comment]
По поводу захардкоженности - ну почему, у тебя получается как бы единый источник передачи данных вниз во вложенные миксины, что как раз норм. Разве что по идее это должно в **index.pug** передаваться, но думаю это излишнее усложнение для учебного проекта. Во всяком случае у меня в проекте было реализовано так же, хотя думаю, ты в курсе и именно на его основе реализовал так )

**Comment by Nelliza** [comment]
Посмотри еще коммент: https://github.com/lndbaryshnikov/resume/commit/7a4b6ae641e4703de25cf435a19e3edc6009d98f#r37194282

**Comment by Nelliza** [comment]
**page.scss**
![1](https://user-images.githubusercontent.com/19621113/74099519-d5c48f00-4b35-11ea-8b81-95bc93889a67.png)
Пустой блок

**Comment by Nelliza** [comment]
То же самое в **progress-list-item.scss** нашла, пустой блок
